project:
  type: website
  output-dir: docs

website:
  title: "BIOL3722_2026"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: show
    code-tools: true
    number-sections: true

params:
  session: 1
  